services:
  api-gate:
    build: .
    container_name: api_gate
    environment:
      - MESSAGEQ_HOST=rabbitmq
      - EXCHANGE_NAME=RIOT_CALLBACKS
    ports:
      - "1337:1337"
    networks:
      - nginx.docker
      - rabbitmq.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true
  rabbitmq.docker:
    name: rabbitmq.docker
    external: true
