services:
  api-gate:
    image: lblcs/api_gate:$VERSION
    container_name: api_gate-$VERSION
    environment:
      - HOST=rabbitmq
    ports:
      - "1337:1337"
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true